In [1]:
import pandas as pd
from pandas_profiling import ProfileReport

In [5]:
source_path = './data/1. 사원 기초정보.xls'
df = pd.read_excel(source_path, header=0, index_col=None)
df

,직원id,2016평가,2017평가,2018평가,부서,사원구분,고용형태,직위,직급,직책,...,제대구분,병과,종교,계급,내외국인,배우자,나이,근속,다자녀추가공제,결혼여부
0,1,NaN,NaN,NaN,화공영업본부,연봉(직원),상용직,전무,임원,본부장,...,NaN,NaN,NaN,NaN,내국인,해당,62,30/10/22,0,NaN
1,2,NaN,NaN,NaN,후공정팀,연봉(현장),상용직,직장,NaN,팀원,...,NaN,NaN,NaN,NaN,내국인,비해당,65,29/06/07,0,NaN
2,3,NaN,NaN,NaN,선행팀(구),연봉(현장),상용직,직장,NaN,팀원,...,NaN,NaN,NaN,NaN,내국인,NaN,57,22/00/06,0,NaN
3,4,NaN,NaN,NaN,자재관리팀,연봉(직원),상용직,부장,NaN,팀원,...,NaN,NaN,기독교,병장,내국인,해당,53,21/06/15,2,기혼
4,5,NaN,NaN,NaN,설비관리팀,시급(현장),상용직,반장,NaN,팀원,...,NaN,NaN,NaN,NaN,내국인,해당,62,17/07/06,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1488,1489,NaN,NaN,NaN,일용직,일급,일용직,일용,NaN,NaN,...,NaN,NaN,NaN,NaN,내국인,NaN,39,00/00/03,0,NaN
1489,1490,NaN,NaN,NaN,일용직,일급,일용직,일용,NaN,NaN,...,NaN,NaN,NaN,NaN,내국인,NaN,39,00/00/03,0,NaN
1490,1491,NaN,NaN,NaN,일용직,일급,일용직,일용,NaN,NaN,...,NaN,NaN,NaN,NaN,내국인,NaN,39,00/00/03,0,NaN
1491,1492,NaN,NaN,NaN,일용직,일급,일용직,일용,NaN,NaN,...,NaN,NaN,NaN,NaN,내국인,NaN,33,00/00/26,0,NaN
1492,1493,NaN,NaN,NaN,일용직,일급,일용직,일용,NaN,NaN,...,NaN,NaN,NaN,NaN,내국인,NaN,39,00/00/09,0,NaN